tasks/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'auth', to: 'auth#check', as: 'check_auth'
  resources :tasks do
    collection do
      get :shuffle
    end

    get :resolve
  end

  root to: redirect('/tasks')
end

tasks/app/models/parrot.rb
class Parrot < ApplicationRecord
end

tasks/app/models/task.rb
class Task < ApplicationRecord
  scope :active, -> { where(status: 'active') }

  has_one :assignee, class_name: 'Parrot', foreign_key: :public_id, primary_key: :assignee_public_id

  after_commit :notify_assigned, if: :assignee_public_id_previously_changed?
  after_commit :notify_resolved, if: :resolved_previously?
  after_create_commit :notify_created
  after_update_commit :notify_updated
  after_destroy_commit :notify_destroyed

  def notify_assigned
    ApplicationMessage.deliver(Tasks::AssignedMessage.new(self))
  end

  def notify_resolved
    ApplicationMessage.deliver(Tasks::ResolvedMessage.new(self))
  end

  def notify_updated
    ApplicationMessage.deliver(Tasks::UpdatedMessage.new(self))
  end

  def notify_created
    ApplicationMessage.deliver(Tasks::RegisteredMessage.new(self))
  end

  def notify_destroyed
    ApplicationMessage.deliver(Tasks::DeletedMessage.new(self))
  end

  def resolved_previously?
    status == 'resolved' && status_previously_changed?
  end
end

tasks/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  helper_method :current_parrot

  def pundit_user
    current_parrot
  end

  def current_parrot
    Parrots::Description.new(session[:parrot])
  end

  def authenticate_parrot!
    return if current_parrot.present?

    redirect_to authentication_url
  end

  def authentication_url
    uri = URI.parse(ENV['AUTH_URL'])
    query = URI.decode_www_form(uri.query.to_s) << ['back_url', check_auth_url]
    uri.query = URI.encode_www_form(query)
    uri.to_s
  end
end

tasks/app/controllers/auth_controller.rb
# frozen_string_literal: true

class AuthController < ApplicationController
  def check
    if params[:token].blank?
      redirect_to authentication_url
      return
    end

    session[:parrot] = Parrots::JwtPayload.new(params[:token])
    redirect_to root_path
  end
end

tasks/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy resolve ]

  helper_method :task_policy

  # GET /tasks or /tasks.json
  def index
    @tasks = policy_scope(Task.all.order(:created_at))
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  def resolve
    authorize(@task)
    Tasks::ResolveTask.call(@task)
    redirect_to tasks_path
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    authorize(@task)

    if @task.save
      redirect_to task_url(@task), notice: 'Task was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    authorize(@task)

    if @task.update(task_params)
      redirect_to task_url(@task), notice: 'Task was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    authorize(@task)
    @task.destroy

    redirect_to tasks_path, notice: 'Task was successfully destroyed.'
  end

  def shuffle
    authorize(current_parrot)
    Tasks::ShuffleTasks.call
    redirect_to tasks_path, notice: 'Tasks are reassigned.'
  end

  private

  def task_policy
    TaskPolicy.new(current_parrot, @task)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id] || params[:task_id] )
  end

  # Only allow a list of trusted parameters through.
  def task_params
    TaskPolicy::Params.new(
      current_parrot,
      params,
      defaults: { assignee_public_id: current_parrot.public_id }
    ).resolve
  end
end

tasks/app/helpers/tasks_helper.rb
module TasksHelper
end

tasks/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

tasks/app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <% if current_parrot.manager? || current_parrot.admin? %>
    <div class="field">
      <%= form.label :assignee_public_id %>
      <%= form.select :assignee_public_id, Parrot.pluck(:name, :public_id) %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tasks/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

tasks/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Current role: <%= current_parrot.role %></h2>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Asignee</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.assignee&.name || 'Not Sync Parrot' %></td>
        <td><%= task.status %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_parrot.manager? || current_parrot.admin? %>
  <%= link_to 'MANAGER: SHUFFLE TASKS', shuffle_tasks_path %> |
<% end %>

<%= link_to 'New Task', new_task_path %>

tasks/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

tasks/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Asignee public:</strong>
  <%= @task.assignee&.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<% @task %>
<%= link_to 'Resolve', task_resolve_path(@task) %> |
<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>